### ISSUE TITLE
error: Package ‘helm-elscreen-’ is unavailable

### ISSUE THREAD

**Issue by k-hoshino** [n9d/emacs.init#3]
自分の自宅用macで `init.el` を試したところ、
下記のエラーが発生しました。

```
Warning (initialization): An error occurred while loading ‘/Users/xxxx/.emacs.d/init.el’:

error: Package ‘helm-elscreen-’ is unavailable
```

`package-install` にて `helm-elscreen` をしたところ、
上記のエラーは出なくなりましたが、
`init.el` の記述で上記の問題を回避できませんでしょうか？

**Comment by n9d** [comment]
なにか問題が起こったときには~/.emacs.d/elpaをまるごと消しちゃったほうが早かったりします。

**Comment by k-hoshino** [comment]
@n9d 

ご回答ありがとうございます。
上記の回答で問題ないので本件クローズします。
